### PR TITLE
RN 0.63 and navigation 4.0.0

### PR DESCRIPTION
**Pull request by SandeshVakale**

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@SandeshVakale Do you know why the tests are failing in CI? Do they pass locally?

**Comment by SandeshVakale** [comment]
Hello @jamonholmgren , I changed node version. now test are passed. If you have any other changes, let me know. Else you can Merge my pull request. thanks

**Comment by DeVoresyah** [comment]
@SandeshVakale thanks for updating to RN 0.63
I've a question about the navigation, does react-navigation v5 still not stable so we just stay at version 4?

**Comment by jamonholmgren** [comment]
Great job @SandeshVakale !

**Comment by SandeshVakale** [comment]
thanks @jamonholmgren

**Pull request merged**
