### PR TITLE
fix(boilerplate): Import AppConfig in App/Config/index.js

### LINKED ISSUE #243: AppConfig not imported
It seems that App/Config/AppConfig.js is no longer imported in App/Config/index.js. This results in I18n not initializing properly.

---
Steps to reproduce
Generate new project with Ignite v 2.1.0 and check App/Config/index.js. There used to be an import there but now it is gone.

### PR DESCRIPTION
**Pull request by bencergazda**
Fixes #243

### CODE REVIEW

**Comment by GantMan** [comment]
This doesn't do anything since this change:   https://github.com/infinitered/ignite-andross/commit/575d24ce42aa3fada4292502e50580f646549686#diff-a0b9a573990653a494ad51bb49ccd7b9L6

**Comment by jamonholmgren** [comment]
@bencergazda I think if you and @lvlrSajjad can coordinate on this, because he took out the import. Importing the config but not doing anything with it trips up the linter.

**Comment by bencergazda** [comment]
@jamonholmgren @GantMan Creating a new project with `$ ignite new TestApp` and selecting `react-native-i18n` as the internationalization library in the CLI, TestApp will have an `import '../I18n/I18n'` line in `./Config/AppConfig.js`. This is needed for the app to pick up the translation source files (`./I18n/languages/*.json`) and the i18n configuration.

I think that after the changes in the linked commit 575d24c ([./Config/index.js](https://github.com/infinitered/ignite-andross/commit/575d24ce42aa3fada4292502e50580f646549686#diff-a0b9a573990653a494ad51bb49ccd7b9)), the import for `./Config/AppConfig.js` became 'unused'  for ESLint, as the usage of the imported file (the `Text.defaultProps.allowFontScaling = AppConfig.allowTextFontScaling` line) got removed. But this also makes react-native-i18n unconfigured, as it's configuration file `../I18n/I18n` nowhere gets imported.

The current PR fails in the CI test only because of adding the import for `./Config/AppConfig` in the current situation breaks ESLint's `no-unused-vars` rule.

If you do not plan to change the original concept, I suggest keeping the `import AppConfig from './AppConfig';` line in its original place in `./Config/index.js` with an `// eslint-disable-line no-unused-vars` comment as a hotfix until the whole i18n thing gets refactored (which I assume, see https://github.com/infinitered/ignite/issues/1319)

**Comment by jamonholmgren** [comment]
Makes sense, @bencergazda . Can you adjust your PR to not fail linting?

**Comment by bencergazda** [comment]
@jamonholmgren Thanks for the feedback, I updated the PR!

**Comment by jamonholmgren** [comment]
Thank you @bencergazda !

**Pull request merged**
