### PR TITLE
A pure container/component design pattern

### PR DESCRIPTION
**Pull request by lvlrSajjad**
Guys 
i think this design pattern helps to better meaning of foldering 
this pattern completely splits containers(just the point that redux and react meat eachother) from components(the pure jsx/es section) so we can test them very easier 
for more info you can just take a look at changed files 
eg :
A container 

```jsx
import { connect } from 'react-redux'
import LaunchScreen from '../Components/LaunchScreen'

const mapStateToProps = (state) => {
  return {
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(LaunchScreen)

```

A component :

```jsx
import React, { Component } from 'react'
import { ScrollView, Text, Image, View } from 'react-native'
import { Images } from '../Themes'

// Styles
import styles from './Styles/LaunchScreenStyles'

export default class LaunchScreen extends Component {
  render () {
    return (
      <View style={styles.mainContainer}>
        <Image source={Images.background} style={styles.backgroundImage} resizeMode='stretch' />
        <ScrollView style={styles.container}>
          <View style={styles.centered}>
            <Image source={Images.launch} style={styles.logo} />
          </View>

          <View style={styles.section} >
            <Image source={Images.ready} />
            <Text style={styles.sectionText}>
              This probably isn't what your app is going to look like. Unless your designer handed you this screen and, in that case, congrats! You're ready to ship. For everyone else, this is where you'll see a live preview of your fully functioning app using Ignite.
            </Text>
          </View>

        </ScrollView>
      </View>
    )
  }
}

```

So here we can test component without intracting with redux suff we can test redux stuff as well

### CODE REVIEW

**Comment by lvlrSajjad** [comment]
> I get this error running `ignite new MyApp -b <path to boilerplate>`
> 
> ```
> ✖ 'from 'react-native'' was not found in file /Users/morgan/dev/testing/App0/App0/App/Containers/LaunchScreen.js.
> ```
> Then at runtime:
> screen shot 2018-12-07 at 3 25 35 pm
> 
> Can you verify that you can build a working app from your fork?
> 
> Thanks Sajjad!

I will check it thanks for run test

**Comment by lvlrSajjad** [comment]
image
Took a run test

**Comment by mlaco** [comment]
@lvlrSajjad please merge master again please

**Comment by jamonholmgren** [comment]
Hey @lvlrSajjad , we decided we won't be merging this pull request into Andross. Thanks so much for your suggestion!

**Pull request closed without merging**
